### Create a new user
POST http://localhost:3000/auth/signup
content-type: application/json

{
    "email": "mcook@yahoo.com",
    "password": "123abdasac"
}

### Find user by ID
GET http://localhost:3000/auth/2

### Find all user by given email
GET http://localhost:3000/auth?email=cook@yahoo.com

### Delete a user with a given id
DELETE http://localhost:3000/auth/2

### Update a user by id
PATCH http://localhost:3000/auth/2
content-type: application/json

{
    "password": "aajjahgagh23433"
}