### List all messages
GET http://localhost:4000/messages


### Create a new message
POST http://localhost:4000/messages
content-type: application/json

{
    "content": "More stuff"
}

### List a single message
GET http://localhost:4000/messages/256a2fc2-85c1-48e8-b580-0646e53dd54d