### List all messages
GET http://localhost:3000/messages


### Create a new message
POST http://localhost:3000/messages
content-type: application/json

{
    "content": "Hi there"
}

### List a single message
GET http://localhost:3000/messages/112