### List all messages
GET http://localhost:4000/messages


### Create a new message
POST http://localhost:4000/messages
content-type: application/json

{
    "content": "This is another message"
}

### List a single message
GET http://localhost:4000/messages/534776c2-515a-4c80-bb6e-d157511710cb