### Create a new report
POST http://localhost:3000/reports
content-type: application/json

{
 
  "price": 34000,
  "make": "Volkswagon",
  "model": "Atlas",
  "year": 2021,
  "long": 0,
  "lat": 0,
  "mileage": 0
}

### Will change approved status of a report
PATCH http://localhost:3000/reports/3
content-type: application/json

{
  "approved": true
}

### Get an Estimate for an existing vechicle
GET http://localhost:3000/reports?make=Volkswagon&model=Atlas&long=0&lat=0&mileage=0&year=2021