### Create a new report
POST http://localhost:3000/reports
content-type: application/json

{
 
  "price": 10000,
  "make": "Toyota",
  "model": "Corolla",
  "year": 2013,
  "long": 0,
  "lat": 0,
  "mileage": 165000
}
